spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      validate: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  main.web-application-type: reactive