spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-demo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  main.web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: swagger-ui
          uri: ${swagger-ui_url}
          predicates:
            - Path=/swagger-ui/**,/swagger-resources/**,/swagger-ui.html,/v2/api-docs,/webjars/**,/view/**

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
server:
  forward-headers-strategy: framework